### PR TITLE
Fix DynamicArrayNode merging

### PR DESCRIPTION
**Pull request by enumag**

### CODE REVIEW

**Comment by enumag** [comment]
This caused a very strange bug causing the DIC compilation to fail when the configuration was merged from 3 or more files.

**Comment by sandrokeil** [comment]
@enumag Thank you very much for your contribution. But this package is superseeded by [event-store-symfony-bundle](https://github.com/prooph/event-store-symfony-bundle) and [service-bus-symfony-bundle](https://github.com/prooph/service-bus-symfony-bundle) which are more Symfony style.

@codeliner Should we deprecate this repo in favor of the others?

**Comment by enumag** [comment]
@sandrokeil I'm aware but from what I've heard they are not exactly finished.

**Comment by enumag** [comment]
@tomcizek Can you elaborate the reasoning why we didn't use those two bundles? You know more about it than I do.

**Comment by codeliner** [comment]
I've added a depricated notice to this package as well.
Our prooph-bundle package already has a notcie and there you can find the answer to your question @enumag : https://github.com/proophsoftware/prooph-bundle#deprecated

But I think we can merge the fix. thx @enumag

**Comment by enumag** [comment]
@codeliner Thanks. Can I ask you to tag a new release?

**Pull request merged**
